### ISSUE TITLE
Avoid Object Mutations

### ISSUE THREAD

**Issue by OlivierCo** [chrisrzhou/egghead-redux#1]
Maybe you mix-up something between ES5 and ES6 and ES7. or maybe i'm wrong.

To avoid object mutations, we should use Object.assign() in ES6 and the spread operator in ES7 ...

this should be:

> To avoid object mutations, we should use Object.assign() in **ES5** and the spread operator in **ES6** ...

**Comment by chrisrzhou** [comment]
Thanks @OlivierCo! These are personal notes for myself, but fixed them based on your suggestion!
